FROM nginx:1.19 as runtime
RUN echo "Advanced configuration started."
RUN echo "<!DOCTYPE html><html><head><title>ezy pezy</title></head><body><h1>This is too easy!</h1></body></html>" > /usr/share/nginx/html/index.html
RUN echo "Configuration completed."
