name: publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "12"
      - name: install marp
        run: npm install @marp-team/marp-cli
      - uses: actions/checkout@v2
      - name: marp generate
        run: make generate
      - name: deploy🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: website
          CLEAN: true
